filebeat.inputs:
  - type: log
    enabled: true
    paths:
     - /logs/service1.log
    fields:
      service: my_service
    fields_under_root: true
    overwrite_keys: true
    multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:|(^[a-zA-Z\]\;\}\{ ]|^\s*$)'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
     - /logs/service2.log
    fields:
      service: my_service2
      customField: stuff
    fields_under_root: true
    overwrite_keys: true
    multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:|(^[a-zA-Z\]\;\}\{} ]|^\s*$)'
    multiline.negate: false
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

setup:
  kibana:
    host: "kibana:5601"
  template.overwrite: true  
